# Generated by Django 3.0.6 on 2020-07-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebKart', '0002_auto_20200704_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='none', max_length=50)),
                ('email', models.CharField(default='none', max_length=50)),
                ('city', models.CharField(default='none', max_length=50)),
                ('state', models.CharField(default='none', max_length=20)),
                ('mobile', models.CharField(default='none', max_length=20)),
                ('suggestion', models.CharField(default='none', max_length=1000)),
            ],
        ),
    ]
