# Generated by Django 3.0.6 on 2020-07-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebKart', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='00000', max_length=50),
        ),
    ]
