# Generated by Django 3.0.6 on 2020-07-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebKart', '0005_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='item_json',
            new_name='items_json',
        ),
    ]
