# Generated by Django 3.0.6 on 2020-07-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebKart', '0007_auto_20200715_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(default='NA', max_length=350),
        ),
    ]
