# Generated by Django 3.0.6 on 2020-07-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebKart', '0008_product_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_specs',
            field=models.CharField(default='NA', max_length=1000),
        ),
    ]
