# Generated by Django 3.0.6 on 2020-07-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebKart', '0009_product_full_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orignal_price',
            field=models.IntegerField(default=0),
        ),
    ]
