# Generated by Django 3.0.6 on 2020-07-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebKart', '0010_product_orignal_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(default='', max_length=2000)),
                ('email', models.CharField(default='NA', max_length=100)),
                ('update_decs', models.CharField(default='no_description', max_length=500)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
