# Generated by Django 3.0.6 on 2020-07-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebKart', '0011_ordersupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersupdate',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ordersupdate',
            name='update_decs',
        ),
        migrations.AddField(
            model_name='ordersupdate',
            name='update_desc',
            field=models.CharField(default='NA', max_length=5000),
        ),
        migrations.AlterField(
            model_name='ordersupdate',
            name='order_id',
            field=models.IntegerField(default=''),
        ),
    ]
